spring:
  application:
    name: at-crew-backend
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017}
    database: ${MONGODB_DATABASE:atcrew}
  data:
    mongodb:
      auto-index-creation: true
  jackson:
    time-zone: Asia/Seoul
