spring:
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}
  data:
    mongodb:
      auto-index-creation: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  secret: ${JWT_SECRET}

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH}

logging:
  level:
    com.atcrew: INFO
