-- 태그 정본 목록 정규화 (recruit) — docs/design/search-module-design.md §1.4/§9-2
--
-- 구인글·팀원모집글·구직글의 roles/genres는 자유 텍스트였고, 검색 필터는 ArtworkRole 상수 이름으로
-- 매칭을 시도해 사실상 아무것도 걸리지 않았다. 세 엔티티의 roles를 ArtworkRole, genres를 Genre로
-- 고정하면서, 정본 밖 값을 제거하고 컬럼 폭을 artwork_roles/artwork_genres(VARCHAR(30))와 맞춘다.
-- 정본은 전부 영문 상수 이름이라 기존 한글 자유 텍스트 중 살아남는 값은 없다(실사용자 데이터 없음).

DELETE FROM job_posting_roles WHERE role NOT IN (
    'TOTAL_ARTWORK', 'ADAPTATION_STORYBOARD', 'STORYBOARD', 'DIRECTION', 'LINEART', 'SKETCH',
    'COLORING', 'BASE_COLOR', 'TONE_WORK', 'POST_PROCESSING', 'FULL_COLOR', 'PANEL_DECORATION',
    'THREE_D_MODELING', 'MATERIAL_MAKING', 'MATERIAL_PLACEMENT', 'BACKGROUND', 'WEBNOVEL_COVER',
    'CHARACTER_DESIGN', 'CHARACTER_SHEET', 'TYPOGRAPHY', 'BROADCAST_THUMBNAIL', 'ETC'
);
DELETE FROM team_posting_roles WHERE role NOT IN (
    'TOTAL_ARTWORK', 'ADAPTATION_STORYBOARD', 'STORYBOARD', 'DIRECTION', 'LINEART', 'SKETCH',
    'COLORING', 'BASE_COLOR', 'TONE_WORK', 'POST_PROCESSING', 'FULL_COLOR', 'PANEL_DECORATION',
    'THREE_D_MODELING', 'MATERIAL_MAKING', 'MATERIAL_PLACEMENT', 'BACKGROUND', 'WEBNOVEL_COVER',
    'CHARACTER_DESIGN', 'CHARACTER_SHEET', 'TYPOGRAPHY', 'BROADCAST_THUMBNAIL', 'ETC'
);
DELETE FROM job_seeking_post_roles WHERE role NOT IN (
    'TOTAL_ARTWORK', 'ADAPTATION_STORYBOARD', 'STORYBOARD', 'DIRECTION', 'LINEART', 'SKETCH',
    'COLORING', 'BASE_COLOR', 'TONE_WORK', 'POST_PROCESSING', 'FULL_COLOR', 'PANEL_DECORATION',
    'THREE_D_MODELING', 'MATERIAL_MAKING', 'MATERIAL_PLACEMENT', 'BACKGROUND', 'WEBNOVEL_COVER',
    'CHARACTER_DESIGN', 'CHARACTER_SHEET', 'TYPOGRAPHY', 'BROADCAST_THUMBNAIL', 'ETC'
);

DELETE FROM job_posting_genres WHERE genre NOT IN (
    'BL', 'HL', 'GL', 'FANTASY', 'ROMANCE_FANTASY', 'ACTION', 'MARTIAL_ARTS', 'GORE', 'HORROR',
    'NOIR', 'CRIME', 'THRILLER', 'MYSTERY', 'SUPERPOWER', 'SF', 'COMEDY', 'HEALING',
    'SLICE_OF_LIFE', 'DRAMA', 'SCHOOL', 'GAME', 'ORIENTAL_SETTING', 'WESTERN_SETTING',
    'PERIOD_HISTORY', 'MEDIEVAL', 'MODERN', 'EROTIC', 'CREATURE', 'YOUTH'
);
DELETE FROM team_posting_genres WHERE genre NOT IN (
    'BL', 'HL', 'GL', 'FANTASY', 'ROMANCE_FANTASY', 'ACTION', 'MARTIAL_ARTS', 'GORE', 'HORROR',
    'NOIR', 'CRIME', 'THRILLER', 'MYSTERY', 'SUPERPOWER', 'SF', 'COMEDY', 'HEALING',
    'SLICE_OF_LIFE', 'DRAMA', 'SCHOOL', 'GAME', 'ORIENTAL_SETTING', 'WESTERN_SETTING',
    'PERIOD_HISTORY', 'MEDIEVAL', 'MODERN', 'EROTIC', 'CREATURE', 'YOUTH'
);
DELETE FROM job_seeking_post_genres WHERE genre NOT IN (
    'BL', 'HL', 'GL', 'FANTASY', 'ROMANCE_FANTASY', 'ACTION', 'MARTIAL_ARTS', 'GORE', 'HORROR',
    'NOIR', 'CRIME', 'THRILLER', 'MYSTERY', 'SUPERPOWER', 'SF', 'COMEDY', 'HEALING',
    'SLICE_OF_LIFE', 'DRAMA', 'SCHOOL', 'GAME', 'ORIENTAL_SETTING', 'WESTERN_SETTING',
    'PERIOD_HISTORY', 'MEDIEVAL', 'MODERN', 'EROTIC', 'CREATURE', 'YOUTH'
);

-- 복합 PK 선두/후행 컬럼이라 MODIFY 시 인덱스가 함께 재구성된다(값이 짧아지기만 하므로 절단 위험 없음).
ALTER TABLE job_posting_roles        MODIFY COLUMN role  VARCHAR(30) NOT NULL;
ALTER TABLE team_posting_roles       MODIFY COLUMN role  VARCHAR(30) NOT NULL;
ALTER TABLE job_seeking_post_roles   MODIFY COLUMN role  VARCHAR(30) NOT NULL;
ALTER TABLE job_posting_genres       MODIFY COLUMN genre VARCHAR(30) NOT NULL;
ALTER TABLE team_posting_genres      MODIFY COLUMN genre VARCHAR(30) NOT NULL;
ALTER TABLE job_seeking_post_genres  MODIFY COLUMN genre VARCHAR(30) NOT NULL;
