CREATE TABLE members
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_email          VARCHAR(255) UNIQUE,
    handle               VARCHAR(255) UNIQUE,

    -- MemberProfile
    name                 VARCHAR(255) NOT NULL,
    profile_image        VARCHAR(500),
    creator_role         VARCHAR(50)  NOT NULL,
    employment_status    VARCHAR(50)  NOT NULL,
    experience_level     VARCHAR(50)  NOT NULL,

    -- MemberPersonalInfo
    birth_date           VARCHAR(20),
    school               VARCHAR(255),
    location             VARCHAR(255),

    -- MemberContact
    contact_email        VARCHAR(255),
    social_media_link    VARCHAR(500),
    twitter              VARCHAR(255),

    -- MemberCareer
    desired_field        VARCHAR(255),
    creative_tools       VARCHAR(500),
    career               TEXT,

    -- 계정 상태
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted_at           TIMESTAMP,
    deleted_login_email  VARCHAR(255),

    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL
);

CREATE TABLE member_keywords
(
    member_id BIGINT       NOT NULL,
    keyword   VARCHAR(255) NOT NULL,
    FOREIGN KEY (member_id) REFERENCES members (id)
);
